name: webfeed
version: 0.7.0
description: webfeed is a dart package for parsing RSS and Atom feeds. Media, DublinCore, iTunes, Syndication namespaces are also supported.
homepage: ""
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  intl: ^0.17.0
  xml: ^6.1.0
dev_dependencies:
  test: ^1.3.0
  http: "^0.13.0"
